### ISSUE TITLE
The token supplied to the function is invalid

### ISSUE THREAD

**Issue by ilapavuluri** [Waffle/waffle#1505]
Hi Team,

I am getting "The token supplied to the function is invalid" in my NTLM authentication code:

//
 securityContext = authProvider.acceptSecurityToken("localhost:9002", "TlRMTVNTUAABAAAAB4IIogAAAA",
                            "NTLM");
//

With this authentication is failing.

This issue is occurring inconsistently, I am using "com.github.dblock.waffle.waffle-jna-1.5" 

Appreciate your help.

Thanks
Ashok.

**Comment by hazendaz** [comment]
@ilapavuluri Please use a supported version.  1.5 is 9 years old.  Please note group id as well changed some time ago.  

```
<dependency>
  <groupId>com.github.waffle</groupId>
  <artifactId>waffle-jna</artifactId>
  <version>3.1.1</version>
</dependency>
```

**Comment by ilapavuluri** [comment]
@hazendaz thank you so much, will this resolves the mentioned error? because this issue is not consistent, sometimes working, but sometimes not.

Thanks
Ashok.

**Comment by hazendaz** [comment]
@ilapavuluri I assume that it will.  A lot has changed in 9 years.  If you are still having issue with latest, then you would want to look through the docs as there are lots of walk throughs and possible ask the user group.  You can find information on all that on the readme.

**Comment by ilapavuluri** [comment]
Thank you so much @hazendaz.

**Comment by ilapavuluri** [comment]
@hazendaz sorry to bother you again, one last question, I upgraded to waffle-jna 3.1.1

Now want to enable logs for them, I am using logback for logging in my application, and I have logback-access1.2.1 and logback-classic 1.2.3, logback-core 1.2.3. I included jcl-over-slf4j-1.7.36.jar, slf4j-api-1.7.36.jar as well.

Even when I add below  statement in my logback.xml file it is not working, and I am not getting waffle related logs.
Appreciate your help. 

Thanks
Ashok.

**Comment by ilapavuluri** [comment]
@hazendaz I am using play framework not tomcat

**Comment by ilapavuluri** [comment]
@hazendaz appreciate your help on this.

**Comment by ilapavuluri** [comment]
Added below in our logback.xml file but no luck:

 <logger name="waffle.servlet" level="ALL">
	<appender-ref ref="DEBUGFILE" />
  </logger>

**Comment by hazendaz** [comment]
I think you need to look through the docs on this repo.  Also maybe debug the app and look more at your logging.  This project isn't doing anything directly with logging and adding something specific is out of scope to even look at.  Typically you would add nothing else for your logging.  So really out of scope on that to be reviewed or looked at here.  I don't use the play framework but this comes with the core portion and should just work.  See the demos package as it has full setup.  You don't actualyl need to code waffle into your product to confirm it works in your environment and I think starting at docs is necessary to assist you here.  Not sure I can assist much beyond that.

**Comment by ilapavuluri** [comment]
@hazendaz ,

I upgraded to latest jars "com.github.waffle.waffle-jna-3.1.1.jar
caffeine-3.0.5.jar
jna-5.10.0.jar
jna-platform-5.10.0.jar"

But the issue still persists, "The token supplied to the function is invalid".

If more than one user access the NTLM authentication we are getting this error. Please do the needful.

Thanks
Ashok.

**Comment by ilapavuluri** [comment]
Here is the exception trace:
ERROR 2022-03-15 14:04:14 [kka.actor.default-dispatcher-6] AuthenticationInterceptor        862 The token supplied to the function is invalid
com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid
	at waffle.windows.auth.impl.WindowsAuthProviderImpl.acceptSecurityToken(WindowsAuthProviderImpl.java:177)
	at com.ca.casm.authentication.AuthenticationInterceptor.getSecurityContext(AuthenticationInterceptor.java:859)
	at com.ca.casm.authentication.AuthenticationInterceptor.access$300(AuthenticationInterceptor.java:98)
	at com.ca.casm.authentication.AuthenticationInterceptor$1.call(AuthenticationInterceptor.java:361)
	at com.ca.casm.authentication.AuthenticationInterceptor$1.call(AuthenticationInterceptor.java:118)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
	at scala.concurrent.impl.Promise.transform(Promise.scala:29)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
	at scala.concurrent.Future.map(Future.scala:287)
	at scala.concurrent.Future.map$(Future.scala:287)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
	at scala.concurrent.Future$.apply(Future.scala:653)
	at play.core.j.JavaAction.apply(JavaAction.scala:138)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:218)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:217)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:403)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:400)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:218)
	at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:217)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:403)
	at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:400)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:357)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

**Comment by ilapavuluri** [comment]
@hazendaz Appreciate your inputs

**Comment by hazendaz** [comment]
862 is likely the return code you are getting which is invalid.  I think you need to debug the code and see what you are getting from windows.  I'm not quite sure what you mean more than one user this happens.  Its working for one user?

**Comment by ilapavuluri** [comment]
@hazendaz if single user tries to hit it is working fine, but if more than one user tries parallelly we are getting the above error.

**Comment by dblock** [comment]
> concurrent calling of acceptSecurityToken api causing this problem, during sequential execution it is working fine.

What did you do to call it sequentially?

**Comment by ilapavuluri** [comment]
Here is my code:
IWindowsAuthProvider authProvider = new WindowsAuthProviderImpl();

    private IWindowsSecurityContext getSecurityContext(Http.Request request) {
        if (logger.isTraceEnabled()) {
            logger.trace("Inside getSecurityContext");
        }

        IWindowsSecurityContext securityContext = null;

        try {
        	//WindowsAuthProviderImpl authProvider = new WindowsAuthProviderImpl();
            String connectionId = request.host() == null ? request.remoteAddress() : request.host();
          
            List<String> headers = request.getHeaders().getAll("Authorization");
           headers.forEach(header->{
        	   String h = header.toString();
        	   logger.trace("ilaas01 ",header.toString());
           });            
            String authorizationHeader = request.getHeader("Authorization"); 
            String securityPackage = getSecurityPackage(authorizationHeader);
            String token = authorizationHeader.substring(securityPackage.length() + 1);

            if (logger.isTraceEnabled()) {
                logger.trace("Inside getSecurityContext ");
                logger.trace(connectionId);
                logger.trace(token);
                logger.trace("authorizationHeader: ",authorizationHeader);
                logger.trace(securityPackage);
            }
            IWindowsComputer cn = authProvider.getCurrentComputer();
            String cnStr = cn.getComputerName();
            logger.trace("computer name [{}]",cnStr);
            IWindowsDomain dn = authProvider.getDomains()[0];
            String dnStr = dn.getTrustTypeString();
            logger.trace("domain name [{}]",dnStr);

            securityContext = authProvider.acceptSecurityToken(connectionId, Base64.decodeBase64(request.getHeader("Authorization").substring(securityPackage.length() + 1)),
                            securityPackage);
        } catch (Exception e) {
            logger.error(e.getLocalizedMessage(),e);
        }

        if (logger.isTraceEnabled()) {
            logger.trace("Return securityContext: " + securityContext);
        }

        return securityContext;
    }



 /**
                             * If authorization header is null, start the NTLM negotiation
                             * else if the Domain controller sends a continue token send the token back to the client
                             * if the authentication is successful then extract the user identity and continue
                             */

                            if (authorizationHeader == null) {   // initiate the ntlm negotiation
                                ctx.response().setHeader("WWW-Authenticate", challenge);
                                addCommonHeadersToResponse(ctx);
                                promiseOfAuthenticationResult.complete(unauthorized());
                            } else {
                                IWindowsSecurityContext securityContext = getSecurityContext(request);

                                if (securityContext != null) {
                                    // send the challenge token to the client if continue required
                                    if (securityContext.isContinue() || securityContext.getToken() != null) {

                                        if (logger.isDebugEnabled()) {
                                            logger.debug("NTLM authentication failed.");
                                        }
                                        

                                        String type2Message = getSecurityPackage(authorizationHeader) + " "
                                            + Base64.encodeBase64String(securityContext.getToken());
                                        ctx.response().setHeader("WWW-Authenticate", type2Message);
                                        ctx.response().setHeader("Connection", "keep-alive");
                                        promiseOfAuthenticationResult.complete(unauthorized());

                                    } else { // authentication successful, extract the user name and continue

**Comment by ilapavuluri** [comment]
@dblock  appreciate your help on this.

**Comment by dblock** [comment]
The connection id looks suspicious. 

If this is a multi-request/response authentication method, that ID needs to be unique since state is stored in between (https://github.com/Waffle/waffle/blob/208077d732dc9081571971f4aca2bdf408b463cb/Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java#L119). So in the case of multiple connections from the same remote address you will get a duplicate IDs that will fail exactly in the way you are observing. 

```
>         String connectionId = request.host() == null ? request.remoteAddress() : request.host();

...

>         securityContext = authProvider.acceptSecurityToken(connectionId, Base64.decodeBase64(request.getHeader("Authorization").substring(securityPackage.length() + 1)),
>                         securityPackage);
```

Try adding the remote port to your connection ID like [here](https://github.com/Waffle/waffle/blob/208077d732dc9081571971f4aca2bdf408b463cb/Source/JNA/waffle-jna/src/main/java/waffle/util/NtlmServletRequest.java#L51), does that help?

**Comment by ilapavuluri** [comment]
@dblock Thank you so much, issue resolved. Please close the issue.
