### ISSUE TITLE
Waffle 3.2.0 - problem --> Provider waffle.util.cache.CaffeineCacheSupplier not a subtype

### ISSUE THREAD

**Issue by bandedos** [Waffle/waffle#1699]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [NegotiateAuthenticator[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:176)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5147)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
		... 43 more
	Caused by: java.util.ServiceConfigurationError: waffle.util.cache.CacheSupplier: **Provider waffle.util.cache.CaffeineCacheSupplier not a subtype**
		at java.util.ServiceLoader.fail(ServiceLoader.java:239)
		at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
		at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
		at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
		at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
		at waffle.util.cache.Cache.newCache(Cache.java:65)
		at waffle.windows.auth.impl.WindowsAuthProviderImpl.<init>(WindowsAuthProviderImpl.java:105)
		at waffle.apache.WaffleAuthenticatorBase.startInternal(WaffleAuthenticatorBase.java:303)
		at waffle.apache.NegotiateAuthenticator.startInternal(NegotiateAuthenticator.java:65)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 48 more

Can someone help me with this. I don't know what is the problem. Thanks.

**Comment by hazendaz** [comment]
are you missing caffeine library by chance?

**Comment by bandedos** [comment]
No, I double checked it.

**Comment by nstig8** [comment]
Did you ever solve or get a resolution for this?  Seeing the same thing and this is the top Google result with no answer.  So frustratring.

**Comment by DaveCarpeneto** [comment]
So FWIW I saw this running with waffle 3.5.0 &  tomcat11.0.5.0. 

Moving to waffle 3.5.1 & tomcat 10.1.39 resolved it. 

In both cases I set things up via the instructions @ https://github.com/waffle/waffle/blob/master/Docs/tomcat/TomcatSingleSignOnValve.md .

I'm assuming some combo in our envs didn't line up with the systems used for QA.

**Comment by hazendaz** [comment]
ok thanks @DaveCarpeneto, I'll go ahead and close this out.  I expect to also be doing another round of releases soon.  For those stuck on spring boot 2, they will get a slight lifeline.  Glad its again working.
