### ISSUE TITLE
Error on SSO based on environment

### ISSUE THREAD

**Issue by mciumac** [Waffle/waffle#1742]
[ErrorSSO.docx](https://github.com/Waffle/waffle/files/9759320/ErrorSSO.docx)

I have a Spring application that uses Spring Waffle SSO. In my dev environment I successfully access the application. But when deploying to Test environment I get the error (attached) when accessing application url. Both environment run WebSphere9.

**Comment by mciumac** [comment]
we are using waffle 1.9.1
It works in my dev on Windows10 , it does not work on Test server that is  on Windows 2012.

**Comment by hazendaz** [comment]
Please use a more recent version as 1.9 is really old.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mciumac** [comment]
Thank you for response. I will upgrade. Does the table of waffle versions that is compatible with window version exist?
Does WebSphere has any effect on waffle functionality and versions?

**Comment by dblock** [comment]
All versions of Waffle (should) work with all versions of Windows.

The error from that doc file:

```
[10/11/22 13:48:41:141 CDT] 00000302 SystemOut     O 2022-10-11T13:48:41,141 [WebContainer : 0] ERROR  com.ibm.ws.webcontainer.webapp - SRVE0293E: [Servlet Error]-[Faces Servlet]: java.lang.NoClassDefFoundError: com.sun.jna.platform.win32.Sspi$CredHandle (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:95)
	at waffle.windows.auth.impl.WindowsCredentialsHandleImpl.initialize(WindowsCredentialsHandleImpl.java:79)
	at waffle.windows.auth.impl.WindowsAuthProviderImpl.acceptSecurityToken(WindowsAuthProviderImpl.java:116)
	at waffle.servlet.spi.NegotiateSecurityFilterProvider.doFilter(NegotiateSecurityFilterProvider.java:127)
	at waffle.servlet.spi.SecurityFilterProviderCollection.doFilter(SecurityFilterProviderCollection.java:147)
	at waffle.spring.NegotiateSecurityFilter.doFilter(NegotiateSecurityFilter.java:98)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.brick.astm.web.filter.LoggerFilter.doFilter(LoggerFilter.java:46)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:966)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\YYY-WA~1\AppData\Local\Temp\jna--313777546\jna7146032522717519553.dll (JVMPORT015E Unable to resolve shared library references - a prerequisite shared library may be missing)
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1460)
	at java.lang.System.load(System.java:590)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.Structure.<clinit>(Structure.java:2078)
	... 42 more
```

Looks like a problem with loading JNA, so the suggestion to try with a newer version first is a good one.

**Comment by mciumac** [comment]
Thanks. 
We fixed the problem for waffle 1.9.1. We had some dll missing on our Windows 2022 server. This version of waffle (1.9.1) depends on a unsupported Visual Studio 2010 (VC++ 10.0) that is why it did not work. We had the latest Visual Studio installed on this server. 
 We are going to upgrade waffle anyway. For the new waffle we ask what version of Visual Studio (VC++) they depend on. The year and architecture (x86 or X64)? Do you should support both architectures?

**Comment by dblock** [comment]
@hazendaz I am surprised a VS C runtime is required anywhere vs. Windows msvcrt.dll that is on all versions. Is this a recent change in JNA?

**Comment by hazendaz** [comment]
On arch level, they should support both still as it all still supports jdk8 and by extension both 32 and 64 bit.

Waffle is likely to go full jdk 11 and that's only 64 bit though.  Many underlying pieces are jumping up so I expect that to continue given where java is now.  Most likely will do one last java 8 then jump up.

Jna was using vc studio 2015 around that time for the build replacing some of msvc.  Assuming given release notes it might have meant more.  Msvc is also used still from what I could tell.

All in all safest bet is to get on 3.x of waffle as it should be otherwise drop in place and there were some larger issues fixed in jna 5 that had direct impact on waffle.  That was likely at version 3 and release notes will state that.  Many other items were fixed too so latest is most stable.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
