### ISSUE TITLE
com.sun.jna.LastErrorException: GetLastError() returned 15105

### ISSUE THREAD

**Issue by mar1u50** [Waffle/waffle#2358]
We have an authentication module that uses Waffle behind the scenes. For one particular customer and one specific user, we encounter the following exception:
```
 GetLastError() returned 15105 com.sun.jna.LastErrorException: GetLastError() returned 15105 at com.sun.jna.platform.win32.Kernel32Util.formatMessage(Kernel32Util.java:199) at com.sun.jna.platform.win32.Kernel32Util.formatMessage(Kernel32Util.java:219) at com.sun.jna.platform.win32.Win32Exception.<init>(Win32Exception.java:69) at com.sun.jna.platform.win32.Win32Exception.<init>(Win32Exception.java:56) at waffle.windows.auth.impl.WindowsAuthProviderImpl.acceptSecurityToken(WindowsAuthProviderImpl.java:168)
```

Everything works as expected for other customers and even for this customer for other users. Any idea what could be wrong? I have already checked the troubleshooting guide but didn't find anything related.

**Comment by mar1u50** [comment]
We discovered in the Event Viewer during a user login attempt the error 0XC0000413 – "Logon Failure: The machine you are logging onto is protected by an authentication firewall. The specified account is not allowed to authenticate to the machine".

The customer said no firewall prevents the user from logging in.

**Comment by mar1u50** [comment]
We were able to resolve this issue, We needed to add users to one AD group which allows access to the domain where the application is located.
