### ISSUE TITLE
NoSuchMethodError setCredentialsHandle in version 1.8.1

### ISSUE THREAD

**Issue by tbelhalfaoui** [Waffle/waffle#331]
Hi,

I am trying to connect to a PostgreSQL database (through Kerberos and Active Directory) from my Windows 7 machine. It works great with version 1.7.3 of waffle, but fails with version 1.8.1 (everything else but waffle version remaining unchanged).

I am running it in Scala 2.10.6 on top of Java 1.8.0 (64 bits). I also have org.postgresql version 9.4.1208.jre7 installed.

Here is the error I get:
`Exception in thread "main" java.lang.NoSuchMethodError: waffle.windows.auth.impl.WindowsSecurityContextImpl.setCredentialsHandle(Lcom/sun/jna/platform/win32/Sspi$CredHandle;)V
    at org.postgresql.sspi.SSPIClient.startSSPI(SSPIClient.java:164)
    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:594)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:208)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
    at org.postgresql.Driver.makeConnection(Driver.java:406)
    at org.postgresql.Driver.connect(Driver.java:274)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)`

I use the following code to connect to the database:
`DriverManager.getConnection("jdbc:postgresql://myhost:5432/mydb", "myuser", "adummypassword")`

Thanks!

Thomas

**Comment by dblock** [comment]
Did you dig this one up? Check the history of https://github.com/dblock/waffle/blob/master/Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java, I am not sure why this was removed, there's probably a good reason.

**Comment by hazendaz** [comment]
Not sure how the error here is occurring.  The method is still there.  The parater to the method is now IWindowsCredentialsHandle.  This was changed due to a handle leak that was discovered.  Is there anything special this code is doing in addition to any provided examples we have?

**Comment by hazendaz** [comment]
closing issue.  this is likely compilation issue in use case.  If compiled on old, that would explain it working there but failing on new as method signature changed to solve handler leak issues.
