### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: FQN

### ISSUE THREAD

**Issue by rboughani** [Waffle/waffle#475]
I have changed the spring Waffle version, to this
    
     <dependency>
        <groupId>com.github.waffle</groupId>
        <artifactId>waffle-spring-security4</artifactId>
        <scope>compile</scope>
        <version>1.8.2</version>
    </dependency>

And i get this error 

         Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [waffle.spring.NegotiateSecurityFilter]: Factory method 'waffleNegotiateSecurityFilter' threw exception; nested exception is java.lang.NoSuchFieldError: FQN
	at   org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 36 common frames omitted
           Caused by: java.lang.NoSuchFieldError: FQN
	at waffle.spring.NegotiateSecurityFilter.<init>(NegotiateSecurityFilter.java:54) ~[waffle-spring-security4-1.8.2.jar:1.8.2]
	at fr.cc.suivireco.general.configuration.WebSecurityConfig.waffleNegotiateSecurityFilter(WebSecurityConfig.java:197) ~[suivireco-core-0.1-SNAPSHOT.jar:na]
	at fr.cc.suivireco.general.configuration.WebSecurityConfig$$EnhancerBySpringCGLIB$$6b1766fb.CGLIB$waffleNegotiateSecurityFilter$7(<generated>) ~[suivireco-core-0.1-SNAPSHOT.jar:na]
	at fr.cc.suivireco.general.configuration.WebSecurityConfig$$EnhancerBySpringCGLIB$$6b1766fb$$FastClassBySpringCGLIB$$104997b0.invoke(<generated>) ~[suivireco-core-0.1-SNAPSHOT.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at fr.cc.suivireco.general.configuration.WebSecurityConfig$$EnhancerBySpringCGLIB$$6b1766fb.waffleNegotiateSecurityFilter(<generated>) ~[suivireco-core-0.1-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 37 common frames omitted

Any idea pls ?

And when i change the version of waffle security3 to 1.8.2, i have the same error

**Comment by darkmanAmazigh** [comment]
I think that is upperCase and lowerCase issue,
Any idea please ?

**Comment by hazendaz** [comment]
well for one, the class doesn't have FQN regardless of upper or lower case.  I need a little more to go on here such as your configuration that is causing this.  Can you provide your configuraton?  Also, how are you trying to use the filter?

**Comment by darkmanAmazigh** [comment]
The filter config is there 
https://github.com/Waffle/waffle/issues/476

**Comment by hazendaz** [comment]
I'm not sure I 100% follow how you go that but FQN is a value assigned to `principalFormat` so possibly you got the value versus field mixed up.  I'm guessing but think our 'waffle-filter' example which shows this usage is something you might be trying to configure.

**Comment by hazendaz** [comment]
closing issue as not reproducable.  Please see docs on spring boot and our spring boot support.
